DROP TABLE IF EXISTS COIN_NAME ;
CREATE TABLE COIN_NAME ( 
   CODE VARCHAR(10) NOT NULL, 
   CH_CODE VARCHAR(10) NOT NULL, 
   CREATE_TIME TIMESTAMP(9)
);
ALTER TABLE COIN_NAME ADD PRIMARY KEY (CODE );
INSERT INTO COIN_NAME (CODE ,CH_CODE ,CREATE_TIME )VALUES  ('USD','新臺幣',CURRENT_TIMESTAMP());
INSERT INTO COIN_NAME (CODE ,CH_CODE ,CREATE_TIME )VALUES  ('GBP','英鎊',CURRENT_TIMESTAMP());
INSERT INTO COIN_NAME (CODE ,CH_CODE ,CREATE_TIME )VALUES  ('EUR', '歐元',CURRENT_TIMESTAMP());
SELECT * FROM COIN_NAME;